version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.18
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Run test
      - go test -v
  post_build:
    commands:
      - echo Build completed on `date`
